# -*- coding: utf-8 -*-
"""app_interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EC5CYB5qwtwrr4FbPfU_hMYmJbdSNQf
"""

# health_app/app_interface.py

import gradio as gr
import pandas as pd

def build_ui():
    """Creates the Gradio UI blocks and returns the app and a dictionary of components."""

    css = """
    body { font-family: 'Arial', sans-serif; background: linear-gradient(135deg, #000000 0%, #00000 100%); color: #ffffff; }
    .gr-block { background-color: rgba(255, 255, 255, 0.1) !important; border-radius: 12px !important; box-shadow: 0 4px 12px rgba(255, 105, 180, 0.3) !important; padding: 20px !important; border: 1px solid #ff69b4 !important; }
    h1, h2, h3 { text-align: center; color: #ff69b4 !important; margin-bottom: 10px !important; text-shadow: 0 0 10px rgba(255, 105, 180, 0.5); }
    .gr-button { background: linear-gradient(45deg, #ff69b4, #ff1493) !important; color: white !important; border: 1px solid #ffffff !important; border-radius: 8px !important; font-weight: bold !important; transition: all 0.3s !important; }
    .gr-button:hover { transform: translateY(-2px); box-shadow: 0 6px 14px rgba(255, 105, 180, 0.5) !important; }
    label { color: #ff69b4 !important; font-weight: bold !important; }
    """

    components = {}

    with gr.Blocks(css=css, theme=gr.themes.Default(primary_hue="pink")) as app:
        gr.Markdown("# 💖 Health Calculator Suite 💖")
        components['current_user_state'] = gr.State(None)

        with gr.Column(visible=True) as login_view:
            with gr.Tabs():
                with gr.TabItem("Login"):
                    gr.Markdown("## Login to Your Account")
                    components['login_user_input'] = gr.Textbox(label="Username", placeholder="e.g., Alex")
                    components['login_password_input'] = gr.Textbox(label="Password", type="password")
                    components['login_button'] = gr.Button("Login")
                    components['login_status_message'] = gr.Markdown("")
                with gr.TabItem("Register"):
                    gr.Markdown("## Create a New Account")
                    components['reg_user_input'] = gr.Textbox(label="Username", placeholder="Choose a username")
                    components['reg_password_input'] = gr.Textbox(label="Password", type="password")
                    components['reg_confirm_password_input'] = gr.Textbox(label="Confirm Password", type="password")
                    components['register_button'] = gr.Button("Register")
                    components['register_status_message'] = gr.Markdown("")
        components['login_view'] = login_view

        with gr.Column(visible=False) as main_app_view:
            with gr.Row():
                components['welcome_message'] = gr.Markdown("Welcome!")
                components['logout_button'] = gr.Button("Logout")

            with gr.Tabs() as tabs:
                with gr.TabItem("My Profile"):
                    gr.Markdown("### Set Up Your Personal Profile")
                    with gr.Row():
                        with gr.Column():
                            components['profile_height_input'] = gr.Number(label="Height (cm)", value=170)
                            components['profile_weight_input'] = gr.Number(label="Latest Weight (kg)", value=70)
                            components['profile_age_input'] = gr.Slider(label="Age", minimum=10, maximum=100, value=25, step=1)
                            components['profile_gender_input'] = gr.Radio(choices=["Male", "Female"], label="Gender", value="Male")
                            components['activity_level_profile'] = gr.Dropdown(choices=["Sedentary", "Lightly active", "Moderately active", "Very active", "Extremely active"], label="Your Usual Activity Level", value="Moderately active")
                            components['save_profile_button'] = gr.Button("Save Profile")
                        with gr.Column():
                            components['profile_status_message'] = gr.Markdown("Profile saved successfully!")

                with gr.TabItem("Log Weight / BMI"):
                    gr.Markdown("### Log New Weight & BMI")
                    gr.Markdown("Enter your current weight here to update your TDEE goal on the comparison chart.")
                    components['weight_input_bmi'] = gr.Number(label="Current Weight (kg)", value=70)
                    components['calculate_bmi_button'] = gr.Button("Log New Weight")
                    components['bmi_output'] = gr.Textbox(label="BMI Value", interactive=False)
                    components['category_output'] = gr.Textbox(label="Category", interactive=False)

                with gr.TabItem("Metabolic Rate Calculator"):
                    gr.Markdown("### Daily Metabolic Rate Calculator")
                    gr.Markdown("This calculates your current metabolic rate based on your saved profile.")
                    with gr.Row():
                        with gr.Column():
                            components['calculate_bmr_button'] = gr.Button("Calculate My Current Metabolic Rate")
                            components['bmr_info_text'] = gr.Markdown()
                        with gr.Column():
                            gr.Markdown("### **Your Results**")
                            components['bmr_output_display'] = gr.Textbox(label="BMR (Basal Metabolic Rate)", interactive=False)
                            components['tdee_output_display'] = gr.Textbox(label="TDEE (Total Daily Energy Expenditure)", interactive=False)
                            gr.Markdown("### **Calorie Targets**")
                            components['loss_output'] = gr.Textbox(label="For Weight Loss", interactive=False)
                            components['maintenance_output'] = gr.Textbox(label="For Maintenance", interactive=False)
                            components['gain_output'] = gr.Textbox(label="For Weight Gain", interactive=False)

                with gr.TabItem("Food Tracker"):
                    gr.Markdown("### Log Food Calories")
                    with gr.Row():
                        with gr.Column(scale=2):
                            components['food_item_input'] = gr.Textbox(label="Food Item", placeholder="e.g., Banana")
                            components['calories_input'] = gr.Number(label="Calories", value=0, precision=0)
                            components['log_button'] = gr.Button("Add Food Entry")
                            components['food_log_df'] = gr.Dataframe(headers=["Date", "Food", "Calories"], label="Your Food Log", interactive=False)

                with gr.TabItem("Historical Graphs"):
                    gr.Markdown("## Your Progress Over Time")
                    gr.Markdown("### Daily BMI History")
                    components['bmi_history_plot'] = gr.LinePlot(x="Date", y="BMI", title="BMI Over Time", tooltip=['Date', 'BMI', 'Weight'])
                    gr.Markdown("### Daily Calorie Intake Status")
                    gr.Markdown("Green bars indicate intake was on or under your TDEE goal. Red bars indicate you went over.")
                    components['calorie_status_plot'] = gr.BarPlot(x="Date", y="Actual Calorie Intake", color="Status", color_map={"Over Goal": "red", "Under/On Goal": "green"}, title="Calorie Intake vs. Daily Goal", y_lim=[0, 4000])

        components['main_app_view'] = main_app_view

    return app, components