# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pNqm-s--HSzm6Je4Vh9LVmRvN3D8K9H
"""

# health_app/config.py

import os

# --- Configuration for Data Persistence ---

# Define the main folder path in Google Drive
DRIVE_FOLDER_PATH = "/content/drive/MyDrive/HealthApp/"

# Define the name of the data file
DATA_FILE = os.path.join(DRIVE_FOLDER_PATH, "user_health_data.pkl")