# -*- coding: utf-8 -*-
"""data_manager.jpynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igxSfCrcEzuKqqr3f08zYqyoqqojDhKv
"""

# health_app/data_manager.py

import os
import pickle
import hashlib
import pandas as pd
import config

def setup_drive_folder():
    """Ensures the data folder exists in Google Drive."""
    if not os.path.exists(config.DRIVE_FOLDER_PATH):
        os.makedirs(config.DRIVE_FOLDER_PATH)

def _hash_password(password):
    """Hashes the password using SHA-256 for secure storage."""
    return hashlib.sha256(password.encode()).hexdigest()

def save_data(data):
    """Saves the main data dictionary to a pickle file."""
    with open(config.DATA_FILE, "wb") as f:
        pickle.dump(data, f)

def load_data():
    """Loads data from the pickle file if it exists, otherwise returns an empty dictionary."""
    if os.path.exists(config.DATA_FILE):
        try:
            with open(config.DATA_FILE, "rb") as f:
                return pickle.load(f)
        except (pickle.UnpicklingError, EOFError):
            return {}  # Return empty dict if file is corrupt or empty
    return {}

# --- Load data at startup ---
# This dictionary will be imported and used by other modules.
user_health_data = load_data()
